language: dart
sudo: required

addons:
  chrome: stable

dart:
  - dev
  - stable

env:
  - TASK=dartanalyzer
  - TASK=dartfmt
  - TASK=test
  - PKG=example TASK=dartanalyzer
  - PKG=example TASK=dartfmt

script: ./tool/travis.sh

matrix:
  exclude:
    - dart: dev
      env: PKG=example TASK=dartfmt
    - dart: dev
      env: TASK=dartfmt

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

cache:
  directories:
    - $HOME/.pub-cache