name: test_webdriver
description: A helper library to write selenium tests using pageobjects.
version: 0.0.2

authors:
  - Doozer Team <dev@doozer.de>

homepage: https://github.com/doozer-de/test_webdriver

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  pageloader: '^2.2.6'
  test: '^0.12.25'
  webdriver: '^1.2.3'
  yaml: '^2.1.11'

dev_dependencies:
  mockito: '^2.2.0'